import { internalMutation, internalQuery } from "./_generated/server";
import { v } from "convex/values";

/**
 * Create a content-free row used only to carry cancellation state while a
 * managed request is running. The row is removed on every terminal path and
 * is addressed by the high-entropy request id generated by the extension.
 */
export const createManagedTrackingRun = internalMutation({
  args: {
    lensId: v.string(),
    runRequestId: v.string(),
  },
  handler: async (ctx, args) => {
    const lensId = args.lensId.trim();
    const runRequestId = args.runRequestId.trim();
    if (!lensId || !runRequestId) {
      throw new Error("Invalid managed tracking run");
    }
    return await ctx.db.insert("runs", {
      lensId,
      status: "pending",
      runRequestId,
      ephemeral: true,
    });
  },
});

export const markRunning = internalMutation({
  args: { runId: v.id("runs") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (run?.ephemeral) await ctx.db.patch(args.runId, { status: "running" });
  },
});

/** Lightweight cancellation poll used by the in-flight provider action. */
export const getCancelStateByRunId = internalQuery({
  args: { runId: v.id("runs") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run?.ephemeral) {
      return { cancelRequestedAt: undefined, status: undefined } as const;
    }
    return {
      cancelRequestedAt: run.cancelRequestedAt,
      status: run.status,
    } as const;
  },
});

export const markCancelled = internalMutation({
  args: { runId: v.id("runs") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run?.ephemeral || run.status === "completed") return;
    await ctx.db.patch(args.runId, { status: "cancelled" });
  },
});

export const removeManagedTrackingRun = internalMutation({
  args: { runId: v.id("runs") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (run?.ephemeral) await ctx.db.delete(args.runId);
  },
});

/**
 * Reached only through the managed cancel HTTP route. The opaque request id
 * addresses the short-lived row. Repeated or late requests are harmless.
 */
export const requestCancelByRunRequestId = internalMutation({
  args: { runRequestId: v.string() },
  handler: async (ctx, args) => {
    const runRequestId = args.runRequestId.trim();
    if (!runRequestId) {
      return { cancelled: false } as const;
    }
    const run = await ctx.db
      .query("runs")
      .withIndex("by_runRequestId", (q) => q.eq("runRequestId", runRequestId))
      .unique();
    if (!run?.ephemeral) return { cancelled: false } as const;
    if (run.status === "completed" || run.status === "failed" || run.status === "cancelled") {
      return { cancelled: false } as const;
    }
    await ctx.db.patch(run._id, { cancelRequestedAt: Date.now() });
    return { cancelled: true } as const;
  },
});
